# Site
# name: "Starya Mobility"
title: # the name of your site, e.g. ACME Corp.
  en: "Starya Mobility"
  kn: "ಸ್ಟಾರ್ಯ ಮೊಬಿಲಿಟಿ"
description: 
  en: "a startup for EV"
  kn: "ಓಂದು ಇವಿ ಸ್ಟಾರ್ಟಪ್"
tagline: 
  en: "Future is Here!"
  kn: "ಭವಿಷ್ಯ ಇಲ್ಲಿದೆ!"

url: "https://starya.in" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. / /home /blog

index:
  en:
  kn: kannada
feed:
  en: /feed.xml
  kn: /feed_kn.xml

# logo: 'https://starya.in/assets/img/brand/white.png'
# logo-alt: 'https://starya.in/assets/img/brand/orange.png'
# favicon-folder: 'https://starya.in/assets/img/favicon'
# splash-videobg: 'https://res.cloudinary.com/gowrav/video/upload/v1587997357/Gallery%20Starya/starya_splash_oqqrjd.mp4'

# googleapis_KEY: 'AIzaSyBgPPCxfvGYCznsH_Pp6DLRjBjcjykUdVI'
# google_analytics: 'UA-xxxxxxxx-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

languages:
  en: English
  kn: ಕನ್ನಡ
include: ["_pages"]
permalink: /:title/ # Unless Overridden by the page front matter
email: staryamobility@gmail.com

# Authors
authors:
  gl:
    name: Gowrav
    display_name: GL
    gravatar: fa1f2ec20f82eeee44e44fd850a1ad62
    email: gowrav@starya.in
    web: https://gowrav.com/about
    twitter: 
    description: ""

  jrk:
    name: Ravi Kumar
    display_name: JRK
    # avatar: /assets/starya/avatar/ravi_avatar.png
    gravatar: 
    email: ravi@starya.in
    web: 
    twitter: 
    description: ""

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  # - jekyll-archives
  # - jekyll-figure
  # - jekyll-paginate
  # - jekyll-sitemap
  # - jekyll-feed


# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'
    
# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true

exclude: [changelog.md, LICENSE, README.md, Gemfile, Gemfile.lock]