# Site
# name: "Starya Mobility"
title: "Starya Mobility" # the name of your site, e.g. ACME Corp.
description: "a startup for EV"
tagline: "Future is Here!"
url: "https://starya.in" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /home /blog
logo: 'https://starya.in/assets/img/brand/white.png'
logo-alt: 'https://starya.in/assets/img/brand/orange.png'
favicon-folder: 'https://starya.in/assets/img/favicon'
splash-videobg: 'https://res.cloudinary.com/gowrav/video/upload/v1587997357/Gallery%20Starya/starya_splash_oqqrjd.mp4'
googleapis_KEY: 'AIzaSyBgPPCxfvGYCznsH_Pp6DLRjBjcjykUdVI'
# google_analytics: 'UA-xxxxxxxx-1'
# disqus: 'demowebsite'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/
email: staryamobility@gmail.com


# Authors
authors:
  gl:
    name: Gowrav
    display_name: GL
    gravatar: fa1f2ec20f82eeee44e44fd850a1ad62
    email: gowrav@starya.in
    web: https://gowrav.com/about
    twitter: 
    description: ""

  jrk:
    name: Ravi Kumar
    display_name: JRK
    gravatar: 
    email: ravi@starya.in
    web: 
    twitter: 
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  # - jekyll-sitemap
  # - jekyll-feed
  - jekyll-seo-tag
  # - jekyll-archives
  # - jekyll-figure
  - jekyll-redirect-from


# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'
    
# Pagination 
paginate: 5
paginate_path: "/blog/page:num/"

# Other
highlighter: rouge
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
# adsense: "disabled"
# adsense-data-ad-client: "ca-pub-3412143450191416"
# adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
# lazyimages: "disabled"

# Post Author Box ("enabled" or "disabled")
# authorbox: "disabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [changelog.md, LICENSE, README.md, Gemfile, Gemfile.lock]