url: "http://192.168.1.6:4000"
baseurl: "/" # the subpath of your site, e.g. /home /blog
logo: 'http://192.168.1.6:4000/assets/img/brand/white.png'
logo-alt: 'http://192.168.1.6:4000/assets/img/brand/orange.png'
favicon-folder: 'http://192.168.1.6:4000/assets/img/favicon'
splash-videobg: 'http://192.168.1.6:4000/assets/video/starya_splash_bg.mp4'
