url: "http://192.168.1.6:4000"
baseurl: "/" # the subpath of your site, e.g. /home /blog
logo: 'http://192.168.1.6:4000/assets/img/brand/white.png'
logo-alt: 'http://192.168.1.6:4000/assets/img/brand/orange.png'
favicon-folder: 'http://192.168.1.6:4000/assets/img/favicon'
splash-videobg: 'https://res.cloudinary.com/gowrav/video/upload/v1587997357/starya_splash_oqqrjd.mp4'
